version: '3.9'
services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html   // thư mục chứa file php là php nên ./php
    depends_on:
      - mysql_db
    restart: always

  mysql_db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: bke_users
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

volumes:
  db_data:
